# Generated by Django 6.0.5 on 2026-06-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
